### ISSUE TITLE
Verify.php: dob validations (day/month/year)

### ISSUE THREAD

**Issue by jcrowe85** [jcrowe85/new-template#112]
- [x] day should only accept digits between 1 and 12
- [x] month should only accept digits between 0 and 31
- [x] year should only accept digits between 1900 and 2017

<img width="465" alt="screen shot 2017-06-03 at 3 26 06 pm" src="https://cloud.githubusercontent.com/assets/26261665/26757480/5045c246-4871-11e7-8c99-9f2017641233.png">

**Comment by jcrowe85** [comment]
@chvamsiannavarapu

**Comment by chvamsiannavarapu** [comment]
- [x] Remove repeated line in How much coverage would you like?
