### ISSUE TITLE
Userdetails: medical section sameaddress should have spaces

### ISSUE THREAD

**Issue by jcrowe85** [jcrowe85/new-template#113]
- [ ] same address should have spacing between address, city, state and zip

I quickly fixed the issue with displaying state/city/zip but we need spaces placed between each. 
Source: userinfo.js
Line: 80

<img width="326" alt="screen shot 2017-06-03 at 5 22 20 pm" src="https://cloud.githubusercontent.com/assets/26261665/26757906/a0b6e678-4881-11e7-86d9-d5ecd66c0eb9.png">

**Comment by chvamsiannavarapu** [comment]
- [x] Chat Icon should open Drift in the footer.
