### ISSUE TITLE
Userdetails: remove extra height between submit and footer

### ISSUE THREAD

**Issue by jcrowe85** [jcrowe85/new-template#115]
- [x] remove height

<img width="901" alt="screen shot 2017-06-03 at 5 36 36 pm" src="https://cloud.githubusercontent.com/assets/26261665/26757963/940404e0-4883-11e7-8306-2347b1073a00.png">

**Comment by chvamsiannavarapu** [comment]
- [x] Footer Change From Usurance, Inc to Usurit, Inc.
